# Set colors as terminal
set -g pane-active-border-style bg=color0
set -g pane-border-style bg=color0
set-window-option -g window-active-style bg=terminal
set-window-option -g window-style bg=color0

# Open panes in current directory 
bind '"' split-window -v -c "#{pane_current_path}"
bind 'h' split-window -h -c "#{pane_current_path}"

set -g base-index 1
set -g pane-base-index 1
set-option -g renumber-windows on

# Mouse options
set -g mouse on

# Set prefix key
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'catppuccin/tmux'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-resurrect'

# Set vi mode
set-window-option -g mode-keys vi

# Create New Window
bind w new-window -n workspace -c "#{pane_current_path}" \; \
  split-window -h -p 25 -t :.1 -c "#{pane_current_path}" \; \
  split-window -v -p 30 -t :.1 -c "#{pane_current_path}" \; \
  split-window -h -p 50 -t :.2 -c "#{pane_current_path}" \; \
  select-pane -t :.1

# KB
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel 

# Cycle windows
bind -n M-H previous-window 
bind -n M-L next-window 

# Decide whether we're in a Vim process
is_vim="ps -o state= -o comm= -t '#{pane_tty}' \
    | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|n?vim?x?)(diff)?$'"

bind-key -n 'C-h' if-shell "$is_vim" 'send-keys C-h' 'select-pane -L'
bind-key -n 'C-j' if-shell "$is_vim" 'send-keys C-j' 'select-pane -D'
bind-key -n 'C-k' if-shell "$is_vim" 'send-keys C-k' 'select-pane -U'
bind-key -n 'C-l' if-shell "$is_vim" 'send-keys C-l' 'select-pane -R'

tmux_version='$(tmux -V | sed -En "s/^tmux ([0-9]+(.[0-9]+)?).*/\1/p")'
if-shell -b '[ "$(echo "$tmux_version < 3.0" | bc)" = 1 ]' \
    "bind-key -n 'C-\\' if-shell \"$is_vim\" 'send-keys C-\\'  'select-pane -l'"
if-shell -b '[ "$(echo "$tmux_version >= 3.0" | bc)" = 1 ]' \
    "bind-key -n 'C-\\' if-shell \"$is_vim\" 'send-keys C-\\\\'  'select-pane -l'"

bind-key -T copy-mode-vi 'C-h' select-pane -L
bind-key -T copy-mode-vi 'C-j' select-pane -D
bind-key -T copy-mode-vi 'C-k' select-pane -U
bind-key -T copy-mode-vi 'C-l' select-pane -R
bind-key -T copy-mode-vi 'C-\' select-pane -l

# Catppuccin theme
set -g @catppuccin_flavor "mocha"
set -g @catppuccin_window_status_style "rounded"
set -g @catppuccin_window_number_position "right"
set -g @catppuccin_window_text " #W"
set -g @catppuccin_window_current_text " #W"
set -g @catppuccin_window_flags "icon"
set -g @catppuccin_status_left_separator "█"
set -g @catppuccin_status_right_separator "█"
set -g @catppuccin_status_connect_separator "no"
set -g @catppuccin_date_time_text "%Y-%m-%d %H:%M"

# Status bar layout
set -g status-position bottom
set -g status-justify left
set -g status-right-length 120
set -g status-left-length 50
set -g status-left "#{E:@catppuccin_status_session}"
set -g status-right "#{E:@catppuccin_status_application}"
set -ag status-right "#{E:@catppuccin_status_user}"
set -ag status-right "#{E:@catppuccin_status_host}"
set -ag status-right "#{E:@catppuccin_status_date_time}"

# Reload config
bind r source-file ~/.config/tmux/tmux.conf \; display-message "Config reloaded!"

# Initialize TPM (keep at the very bottom)
run '~/.config/tmux/plugins/tpm/tpm'
